name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validation & Plan
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 3. Terraform Format Check
        run: terraform fmt -check

      - name: 4. Terraform Init
        run: terraform init

      - name: 5. Terraform Validate
        run: terraform validate

      - name: 6. Terraform Plan
        run: terraform plan -no-color
        continue-on-error: true